# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
name: $(MajorVersion).$(MinorVersion).$(Year:yy)$(DayOfYear)$(Rev:.rr)

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'
  MajorVersion: '1'
  MinorVersion: '0'
  Patch: '0'

steps:
# Restore NuGet packages
- task: DotNetCoreCLI@2
  displayName: Restore NuGet Packages
  inputs:
    projects: '**/*.csproj'
    command: restore
    
- task: richardfennellBM.BM-VSTS-Versioning-Task.Version-DotNetCoreAssemblies-Task.VersionDotNetCoreAssemblies@2
  displayName: 'Version .NET Core Assemblies'

# Compile
- task: DotNetCoreCLI@2
  displayName: Compile
  inputs:
    projects: '**/*.csproj'
    command: build
    arguments: '--configuration $(buildConfiguration)'
    
# Tests
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
    
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    projects: '**/*.csproj'
    command: publish
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: true
    modifyOutputPath: true
    
# Publish the artifacts
- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
